import React from "react";
import { createIcon } from "@gluestack-ui/icon";
export declare const UIIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<(Omit<any, "ref"> & React.RefAttributes<unknown>) | {
    fill?: import("react-native").ColorValue | undefined;
    stroke?: import("react-native").ColorValue | undefined;
}>;
export declare const Icon: React.ForwardRefExoticComponent<Omit<any, "ref"> & React.RefAttributes<unknown>>;
type ParameterTypes = Omit<Parameters<typeof createIcon>[0], "Root">;
declare const createIconUI: ({ ...props }: ParameterTypes) => React.ForwardRefExoticComponent<Omit<any, "ref"> & React.RefAttributes<unknown>>;
export { createIconUI as createIcon };
declare const AddIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { AddIcon };
declare const AlertCircleIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { AlertCircleIcon };
declare const ArrowUpIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const ArrowDownIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const ArrowRightIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const ArrowLeftIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { ArrowUpIcon, ArrowDownIcon, ArrowRightIcon, ArrowLeftIcon };
declare const AtSignIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { AtSignIcon };
declare const BellIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { BellIcon };
declare const CalendarDaysIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { CalendarDaysIcon };
declare const CheckIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const CheckCircleIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { CheckIcon, CheckCircleIcon };
declare const ChevronUpIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const ChevronDownIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const ChevronLeftIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const ChevronRightIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const ChevronsLeftIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const ChevronsRightIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const ChevronsUpDownIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { ChevronUpIcon, ChevronDownIcon, ChevronLeftIcon, ChevronRightIcon, ChevronsLeftIcon, ChevronsRightIcon, ChevronsUpDownIcon, };
declare const CircleIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { CircleIcon };
declare const ClockIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { ClockIcon };
declare const CloseIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const CloseCircleIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { CloseIcon, CloseCircleIcon };
declare const CopyIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { CopyIcon };
declare const DownloadIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { DownloadIcon };
declare const EditIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { EditIcon };
declare const EyeIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const EyeOffIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { EyeIcon, EyeOffIcon };
declare const FavouriteIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { FavouriteIcon };
declare const GlobeIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { GlobeIcon };
declare const GripVerticalIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { GripVerticalIcon };
declare const HelpCircleIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { HelpCircleIcon };
declare const InfoIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { InfoIcon };
declare const LinkIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const ExternalLinkIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { LinkIcon, ExternalLinkIcon };
declare const LoaderIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { LoaderIcon };
declare const LockIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { LockIcon };
declare const MailIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { MailIcon };
declare const MenuIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { MenuIcon };
declare const MessageCircleIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { MessageCircleIcon };
declare const MoonIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { MoonIcon };
declare const PaperclipIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { PaperclipIcon };
declare const PhoneIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { PhoneIcon };
declare const PlayIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { PlayIcon };
declare const RemoveIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { RemoveIcon };
declare const RepeatIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
declare const Repeat1Icon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { RepeatIcon, Repeat1Icon };
declare const SearchIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { SearchIcon };
declare const SettingsIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { SettingsIcon };
declare const ShareIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { ShareIcon };
declare const SlashIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { SlashIcon };
declare const StarIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { StarIcon };
declare const SunIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { SunIcon };
declare const ThreeDotsIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { ThreeDotsIcon };
declare const TrashIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { TrashIcon };
declare const UnlockIcon: import("@gluestack-ui/icon/lib/typescript/createIcon").IIconComponentType<any>;
export { UnlockIcon };
